### ISSUE TITLE
Singleton options may be broken

### ISSUE THREAD

**Issue by adrianparvino** [nix-gui/nix-gui#94] opened 2021-08-11 16:51 UTC
https://github.com/nix-gui/nix-gui/pull/80/files#diff-d0d6622e4d148a2bd4c8868338287e7ac39d8c1a3c6da3b46f4841f9ae2323fcR61-R67

![2021-08-12-004135_1920x1050_scrot](https://user-images.githubusercontent.com/25182803/129070364-ebd6643c-2acc-41bd-a223-7e5f366aec4f.png)

**Comment by lapp0** [comment] 2021-08-11 20:24
Because "undefined" isn't pressed down?

**Comment by adrianparvino** [comment] 2021-08-11 20:28
`services.das_watchdog` is not the option itself. 

The option is `services.das_watchdog.enable` however, what gets mounted on the right column is `services.das_watchdog`.

**Comment by lapp0** [comment] 2021-08-14 06:02
Dupe of https://github.com/nix-gui/nix-gui/issues/91

**Closed** 2021-08-19 14:16 UTC
